name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          [
            frontend-nextjs,
            auth-service,
            user-service,
            post-service,
            media-service,
            notification-service,
            chat-service,
          ]
    defaults:
      run:
        working-directory: apps/${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Build Docker Image
        run: docker build -t ${{ matrix.service }} .
