name: CI - Build and Push to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: auth-service
            path: apps/auth-service
          - name: user-service
            path: apps/user-service
          - name: post-service
            path: apps/post-service
          - name: notification-service
            path: apps/notification-service
          - name: chat-service
            path: apps/chat-service
          - name: media-service
            path: apps/media-service
          - name: api-gateway
            path: api-gateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}
          IMAGE_TAG=${{ github.sha }}
          docker build -f ${{ matrix.path }}/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
          echo "$IMAGE_TAG" > image-tag.txt
      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-image-tag
          path: image-tag.txt
