name: Terraform Infra CI

on:
  workflow_run:
    workflows: ["CI - Build and Push to GHCR"]
    types:
      - completed

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download image tag artifact (auth-service)
        uses: actions/download-artifact@v4
        with:
          name: auth-service-image-tag
          path: .
      - name: Download image tag artifact (user-service)
        uses: actions/download-artifact@v4
        with:
          name: user-service-image-tag
          path: .
      - name: Download image tag artifact (post-service)
        uses: actions/download-artifact@v4
        with:
          name: post-service-image-tag
          path: .
      - name: Download image tag artifact (notification-service)
        uses: actions/download-artifact@v4
        with:
          name: notification-service-image-tag
          path: .
      - name: Download image tag artifact (chat-service)
        uses: actions/download-artifact@v4
        with:
          name: chat-service-image-tag
          path: .
      - name: Download image tag artifact (media-service)
        uses: actions/download-artifact@v4
        with:
          name: media-service-image-tag
          path: .
      - name: Download image tag artifact (api-gateway)
        uses: actions/download-artifact@v4
        with:
          name: api-gateway-image-tag
          path: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply (auto-approved)
        run: terraform apply -auto-approve \
          -var="ghcr_username=${{ secrets.GHCR_USERNAME }}" \
          -var="ghcr_pat=${{ secrets.GHCR_PAT }}" \
          -var="db_username=${{ secrets.DB_USERNAME }}" \
          -var="db_password=${{ secrets.DB_PASSWORD }}" \
          -var="auth_service_image_tag=$(cat auth-service-image-tag/image-tag.txt)" \
          -var="user_service_image_tag=$(cat user-service-image-tag/image-tag.txt)" \
          -var="post_service_image_tag=$(cat post-service-image-tag/image-tag.txt)" \
          -var="notification_service_image_tag=$(cat notification-service-image-tag/image-tag.txt)" \
          -var="chat_service_image_tag=$(cat chat-service-image-tag/image-tag.txt)" \
          -var="media_service_image_tag=$(cat media-service-image-tag/image-tag.txt)" \
          -var="api_gateway_image_tag=$(cat api-gateway-image-tag/image-tag.txt)"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
